language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

compiler:
  - clang
  - gcc

os:
    - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake ragel libssl-dev libbotan1.10-dev libboost-dev ninja-build

#install: make install-deps

before_script:
  - mkdir build
  - cd build && cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G Ninja ..

script: pwd && ninja-build imapdl ut && ./ut

notifications:
    email: true

