language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

compiler:
  - clang
  - gcc

os:
    - linux

# Currently, Travis-CI's environment has Ubuntu 12.04 LTS x86-64
# where libboost-dev is too old
# libboost1.55-dev comes from a ppa

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake ragel libssl-dev libbotan1.10-dev ninja-build
  - sudo apt-get install -qq libboost1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev libboost-regex1.55-dev libboost-test1.55-dev libboost-program-options1.55-dev libboost-serialization1.55-dev libboost-log1.55-dev libboost-thread1.55-dev libboost-locale1.55-dev libboost-regex1.55-dev

#install: make install-deps

before_script:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

script: pwd && make imapdl ut && ./ut

notifications:
    email: true

